export const $ = (s,root=document)=>root.querySelector(s);
export const $$ = (s,root=document)=>Array.from(root.querySelectorAll(s));
export function h(value) {return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function date(value,short=false) {if(!value)return '—';return new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',day:'2-digit',month:'short',year:short?undefined:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}
const paths={map:'M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3V6zm6-3v15m6-12v15',work:'M4 7h16v14H4V7zm4 0V3h8v4M9 13l2 2 4-4',users:'M16 21v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2m13-14a4 4 0 010 8m7 6v-2a4 4 0 00-3-4M13 7a4 4 0 11-8 0 4 4 0 018 0',list:'M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01',alert:'M12 3L2 21h20L12 3zm0 6v5m0 3h.01',queue:'M4 4h16v16H4V4zm4 8h8m-4-4v8',logout:'M9 5H3v14h6m4-14l7 7-7 7m-6-7h13',download:'M12 3v12m-5-5l5 5 5-5M4 17v4h16v-4',camera:'M3 7h4l2-3h6l2 3h4v14H3V7zm9 3a4 4 0 100 8 4 4 0 000-8',chevron:'M6 9l6 6 6-6',sun:'M12 3v2m0 14v2M3 12h2m14 0h2M6 6l1 1m10 10l1 1M6 18l1-1M17 7l1-1M16 12a4 4 0 11-8 0 4 4 0 018 0'};
export function icon(name) {return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[name]||paths.list)+'"/></svg>';}
export function toast(message,error=false) {const box=$('#toast');box.textContent=message;box.classList.toggle('error',error);box.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.hidden=true,error?10000:5000);}
export function report(error) {toast(error.message||String(error),true);}
export function busy(button,value,label='Menyimpan') {if(!button)return;if(value){button.dataset.old=button.textContent;button.disabled=true;button.textContent=label;}else{button.disabled=false;button.textContent=button.dataset.old||'Simpan';}}
export function options(rows,selected='',blank='Semua') {return '<option value="">'+h(blank)+'</option>'+rows.map(r=>'<option value="'+h(r.id)+'"'+(r.id===selected?' selected':'')+'>'+h(r.name)+'</option>').join('');}
export function table(headers,rows,cells) {return '<div class="table-scroll"><table><thead><tr>'+headers.map(x=>'<th scope="col">'+h(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cells(r).map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'+(rows.length?'':'<p class="empty">Belum ada data untuk filter ini.</p>');}
export function badge(value) {return '<span class="badge '+(['VALID','active','AKTIF'].includes(value)?'good':'warn')+'">'+h(value||'—')+'</span>';}
export function debounce(fn,ms=350) {let timer;return (...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),ms);};}
export function field(label,name,type='text',value='',attrs='') {return '<label>'+h(label)+'<input name="'+h(name)+'" type="'+h(type)+'" value="'+h(value)+'" '+attrs+'></label>';}
export function dialog(title,html,onSubmit) {
  const dlg=$('#dialog');dlg.oncancel=null;dlg.innerHTML='<form method="dialog"><div class="dialog-head"><h2>'+h(title)+'</h2><button type="button" data-close aria-label="Tutup">×</button></div><div class="dialog-body">'+html+'</div><p class="form-error" role="alert"></p><div class="dialog-actions"><button type="button" data-close>Tutup</button>'+(onSubmit?'<button class="primary" type="submit">Simpan</button>':'')+'</div></form>';
  $$('[data-close]',dlg).forEach(b=>b.onclick=()=>dlg.close());dlg.showModal();
  $('form',dlg).onsubmit=async e=>{e.preventDefault();if(!onSubmit){dlg.close();return;}const b=$('[type=submit]',dlg);busy(b,true);try{await onSubmit(Object.fromEntries(new FormData(e.target)),dlg);dlg.close();}catch(err){$('.form-error',dlg).textContent=err.message;}finally{busy(b,false);}};
  return dlg;
}
export function confirmAction(title,message,action) {return new Promise(resolve=>{dialog(title,'<p>'+h(message)+'</p>',async()=>{await action();resolve(true);});$('#dialog').addEventListener('close',()=>resolve(false),{once:true});});}
const scripts=new Map();
export function loadScript(url) {if(scripts.has(url))return scripts.get(url);const p=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.crossOrigin='anonymous';s.onload=resolve;s.onerror=()=>{scripts.delete(url);s.remove();reject(new Error('Library tidak dapat dimuat. Periksa internet lalu coba kembali.'));};document.head.append(s);});scripts.set(url,p);return p;}
export function combobox(root,name,rows,initial='',other='') {
  const selected=rows.find(r=>r.id===initial),id='combo-'+name;
  root.innerHTML='<label for="'+id+'">'+h(name==='sob_id'?'SOB':'Pekerjaan')+'</label><div class="combo"><input id="'+id+'" autocomplete="off" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="'+id+'-list" value="'+h(initial==='OTHER'?'Lainnya':selected?.name||'')+'" required><input type="hidden" name="'+name+'" value="'+h(initial)+'"><ul id="'+id+'-list" role="listbox" hidden></ul></div><label class="other-label" '+(initial==='OTHER'?'':'hidden')+'>Tulis lainnya<input name="'+(name==='sob_id'?'sob_other':'job_other')+'" value="'+h(other)+'" maxlength="100" '+(initial==='OTHER'?'required':'')+'></label>';
  const input=$('[role=combobox]',root),list=$('ul',root),hidden=$('[type=hidden]',root),free=$('.other-label input',root);let index=-1,visible=[];
  function pick(r){hidden.value=r.id;input.value=r.name;input.setCustomValidity('');list.hidden=true;input.setAttribute('aria-expanded','false');$('.other-label',root).hidden=r.id!=='OTHER';free.required=r.id==='OTHER';if(r.id==='OTHER')free.focus();else input.focus();}
  function render(){visible=rows.concat({id:'OTHER',name:'Lainnya'}).filter(r=>r.name.toLowerCase().includes(input.value.toLowerCase()));list.innerHTML=visible.map((r,i)=>'<li id="'+id+'-'+i+'" role="option" aria-selected="false" data-index="'+i+'">'+h(r.name)+'</li>').join('');index=-1;list.hidden=false;input.setAttribute('aria-expanded','true');}
  input.onfocus=()=>{const old=input.value;input.value='';render();input.value=old;};input.oninput=()=>{hidden.value='';input.setCustomValidity('Pilih salah satu pilihan dari daftar.');render();};
  input.onkeydown=e=>{if(e.key==='Escape'){list.hidden=true;input.setAttribute('aria-expanded','false');}if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(list.hidden)render();index=Math.max(0,Math.min(visible.length-1,index+(e.key==='ArrowDown'?1:-1)));$$('li',list).forEach((li,i)=>{li.setAttribute('aria-selected',String(i===index));if(i===index){input.setAttribute('aria-activedescendant',li.id);li.scrollIntoView({block:'nearest'});}});}if(e.key==='Enter'&&!list.hidden&&index>=0){e.preventDefault();pick(visible[index]);}};
  list.onpointerdown=e=>{const li=e.target.closest('[data-index]');if(li){e.preventDefault();pick(visible[Number(li.dataset.index)]);}};
  input.onblur=()=>setTimeout(()=>{list.hidden=true;input.setAttribute('aria-expanded','false');if(!hidden.value)input.setCustomValidity('Pilih salah satu pilihan dari daftar.');},160);
}
